from __future__ import annotations

import logging
import sys
from argparse import SUPPRESS
from typing import Dict, List, Tuple

from binarylane.console.commands import descriptors
from binarylane.console.metadata import program_name
from binarylane.console.runners import Context, Runner

logger = logging.getLogger(__name__)


def _build_tree() -> Dict[str, List[Tuple[str, str]]]:
    """Build a mapping of command path prefixes to (child_name, description) pairs."""
    raw: Dict[str, Dict[str, str]] = {}

    for descriptor in descriptors:
        words = descriptor.name.split()
        for i in range(len(words)):
            prefix = " ".join(words[:i])
            child = words[i]
            raw.setdefault(prefix, {})
            if i == len(words) - 1:
                raw[prefix][child] = descriptor.description
            elif child not in raw[prefix]:
                raw[prefix][child] = f"Access {child} commands"

    return {k: sorted(v.items()) for k, v in sorted(raw.items())}


def _extract_command_options() -> Dict[str, List[Tuple[str, str]]]:
    """Extract options for each leaf command by loading and configuring it."""
    options_map: Dict[str, List[Tuple[str, str]]] = {}

    for descriptor in descriptors:
        try:
            context = Context()
            context.name = descriptor.name
            context.description = descriptor.description
            cmd = descriptor.runner_type(context)
            cmd._parser.configure()

            opts: List[Tuple[str, str]] = []
            seen: set = set()
            for action in cmd._parser._actions:
                opt_strs = [s for s in action.option_strings if s.startswith("--")]
                if not opt_strs or action.help == SUPPRESS:
                    continue
                opt = opt_strs[0]
                if opt in seen:
                    continue
                seen.add(opt)
                help_text = action.help or ""
                if "%" in help_text:
                    try:
                        help_text = help_text % {
                            "choices": ", ".join(str(c) for c in (action.choices or [])),
                            "default": str(action.default) if action.default is not None else "",
                        }
                    except (KeyError, TypeError):
                        pass
                opts.append((opt, help_text))

            key = descriptor.name.replace(" ", "_")
            options_map[key] = sorted(opts)
        except Exception:
            logger.debug("Failed to extract options for %s", descriptor.name, exc_info=True)

    return options_map


def _bash_escape(s: str) -> str:
    """Escape for use inside bash double quotes."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")


def _generate_bash(prog: str) -> str:
    tree = _build_tree()
    options_map = _extract_command_options()

    # Subcommand case entries
    sub_entries: List[str] = []
    for prefix, children in tree.items():
        pattern = prefix.replace(" ", "_") if prefix else ""
        items = "\n".join(f'            "{name}:{_bash_escape(desc)}"' for name, desc in children)
        sub_entries.append(f'        "{pattern}") completions=(\n{items}\n            ) ;;')
    sub_cases = "\n".join(sub_entries)

    # Option case entries
    opt_entries: List[str] = []
    for cmd_key, opts in sorted(options_map.items()):
        if not opts:
            continue
        items = "\n".join(f'            "{opt}:{_bash_escape(desc)}"' for opt, desc in opts)
        opt_entries.append(f'        "{cmd_key}") completions=(\n{items}\n            ) ;;')
    opt_cases = "\n".join(opt_entries)

    return f"""\
# bash completion for {prog}
# Generated by: {prog} completion bash
#
# Usage: eval "$({prog} completion bash)"
# Or:    {prog} completion bash > /etc/bash_completion.d/{prog}

__bl_format() {{
    # Filter completions array by cur prefix and format with descriptions
    local -a items=("$@")
    local -a matches=()
    local entry comp
    for entry in "${{items[@]}}"; do
        comp="${{entry%%:*}}"
        if [[ "$comp" == "$cur"* ]]; then
            matches+=("$entry")
        fi
    done

    if [[ ${{#matches[@]}} -eq 0 ]]; then
        return
    elif [[ ${{#matches[@]}} -eq 1 ]]; then
        COMPREPLY=("${{matches[0]%%:*}}")
    else
        local maxlen=0
        for entry in "${{matches[@]}}"; do
            comp="${{entry%%:*}}"
            (( ${{#comp}} > maxlen )) && maxlen=${{#comp}}
        done
        local desc min_width=$(( (${{COLUMNS:-80}} + 1) / 2 + 1 ))
        for entry in "${{matches[@]}}"; do
            comp="${{entry%%:*}}"
            desc="${{entry#*:}}"
            printf -v line "%-*s  # %s" "$maxlen" "$comp" "$desc"
            printf -v line "%-*s" "$min_width" "$line"
            COMPREPLY+=("$line")
        done
    fi
}}

_{prog}_completions() {{
    local cur prev words cword
    _init_completion 2>/dev/null || {{
        COMPREPLY=()
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        cword=$COMP_CWORD
        words=("${{COMP_WORDS[@]}}")
    }}

    # Build command path from non-option arguments (skip program name)
    local cmd_path=""
    local i=1
    while [[ $i -lt $cword ]]; do
        local word="${{words[$i]}}"
        case "$word" in
            -*) ;;
            *)
                if [[ -n "$cmd_path" ]]; then
                    cmd_path="${{cmd_path}}_${{word}}"
                else
                    cmd_path="${{word}}"
                fi
                ;;
        esac
        ((i++))
    done

    # Complete options when current word starts with -
    if [[ "$cur" == -* ]]; then
        local -a completions=()
        local try_path="$cmd_path"
        while true; do
            case "$try_path" in
{opt_cases}
            esac
            if [[ ${{#completions[@]}} -gt 0 ]]; then break; fi
            local shorter="${{try_path%_*}}"
            if [[ "$shorter" == "$try_path" ]]; then break; fi
            try_path="$shorter"
        done
        if [[ ${{#completions[@]}} -eq 0 ]]; then
            completions=(
                "--help:Display command options and descriptions"
                "--context:Name of authentication context"
                "--api-token:API token to use with BinaryLane API"
            )
        fi
        __bl_format "${{completions[@]}}"
        return
    fi

    # Complete subcommands
    local -a completions=()
    case "$cmd_path" in
{sub_cases}
    esac
    __bl_format "${{completions[@]}}"
}}

complete -o default -F _{prog}_completions {prog}
"""


def _zsh_escape(s: str) -> str:
    """Escape for use inside zsh single quotes."""
    return s.replace("'", "'\\''")


def _generate_zsh(prog: str) -> str:
    tree = _build_tree()
    options_map = _extract_command_options()

    # Subcommand case entries
    sub_entries: List[str] = []
    for prefix, children in tree.items():
        pattern = prefix.replace(" ", "_") if prefix else ""
        items = "\n".join(f"            '{name}:{_zsh_escape(desc)}'" for name, desc in children)
        sub_entries.append(f'        "{pattern}") commands=(\n{items}\n            ) ;;')
    sub_cases = "\n".join(sub_entries)

    # Option case entries
    opt_entries: List[str] = []
    for cmd_key, opts in sorted(options_map.items()):
        if not opts:
            continue
        items = "\n".join(f"            '{opt}[{_zsh_escape(desc)}]'" for opt, desc in opts)
        opt_entries.append(f'        "{cmd_key}") options=(\n{items}\n            ) ;;')
    opt_cases = "\n".join(opt_entries)

    return f"""\
#compdef {prog}
# Generated by: {prog} completion zsh
#
# Usage: eval "$({prog} completion zsh)"
# Or:    {prog} completion zsh > ${{fpath[1]}}/_{prog}

_{prog}() {{
    local cmd_path=""
    local i=2
    while [[ $i -lt $CURRENT ]]; do
        case "${{words[$i]}}" in
            -*) ;;
            *) cmd_path="${{cmd_path:+${{cmd_path}}_}}${{words[$i]}}" ;;
        esac
        ((i++))
    done

    if [[ "${{words[$CURRENT]}}" == -* ]]; then
        local -a options=()
        local try_path="$cmd_path"
        while true; do
            case "$try_path" in
{opt_cases}
            esac
            if [[ ${{#options[@]}} -gt 0 ]]; then break; fi
            local shorter="${{try_path%_*}}"
            if [[ "$shorter" == "$try_path" ]]; then break; fi
            try_path="$shorter"
        done
        if [[ ${{#options[@]}} -eq 0 ]]; then
            options=(
                '--help[Display command options and descriptions]'
                '--context[Name of authentication context]'
                '--api-token[API token to use with BinaryLane API]'
            )
        fi
        _describe 'option' options
        return
    fi

    local -a commands=()
    case "$cmd_path" in
{sub_cases}
    esac

    _describe 'command' commands
}}

_{prog} "$@"
"""


SHELLS = {"bash": _generate_bash, "zsh": _generate_zsh}


class Command(Runner):
    def run(self, args: List[str]) -> None:
        prog = program_name()

        if not args or args == [Runner.HELP]:
            shells = ", ".join(SHELLS)
            print(f"Usage: {self._context.prog} <{shells}>")
            print()
            print("Generate shell completion scripts.")
            print()
            print("Available shells:")
            print(f"  bash    Generate bash completion script")
            print(f"  zsh     Generate zsh completion script")
            print()
            print(f'Bash: eval "$({prog} completion bash)"')
            print(f'Zsh:  eval "$({prog} completion zsh)"')
            return

        shell = args[0]
        if shell == Runner.CHECK:
            return

        generator = SHELLS.get(shell)
        if generator is None:
            shells = ", ".join(SHELLS)
            print(f"Unsupported shell: {shell}", file=sys.stderr)
            print(f"Supported shells: {shells}", file=sys.stderr)
            raise SystemExit(1)

        print(generator(prog))
