from __future__ import annotations

import sys
from typing import Dict, List, Tuple

from binarylane.console.commands import descriptors
from binarylane.console.metadata import program_name
from binarylane.console.runners import Runner


def _build_tree() -> Dict[str, List[Tuple[str, str]]]:
    """Build a mapping of command path prefixes to (child_name, description) pairs."""
    raw: Dict[str, Dict[str, str]] = {}

    for descriptor in descriptors:
        words = descriptor.name.split()
        for i in range(len(words)):
            prefix = " ".join(words[:i])
            child = words[i]
            raw.setdefault(prefix, {})
            if i == len(words) - 1:
                raw[prefix][child] = descriptor.description
            elif child not in raw[prefix]:
                raw[prefix][child] = f"Access {child} commands"

    return {k: sorted(v.items()) for k, v in sorted(raw.items())}


def _bash_escape(s: str) -> str:
    """Escape for use inside bash double quotes."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")


def _generate_bash(prog: str) -> str:
    tree = _build_tree()

    case_entries: List[str] = []
    for prefix, children in tree.items():
        pattern = prefix.replace(" ", "_") if prefix else ""
        items = "\n".join(
            f'            "{name}:{_bash_escape(desc)}"' for name, desc in children
        )
        case_entries.append(f'        "{pattern}") completions=(\n{items}\n            ) ;;')

    cases = "\n".join(case_entries)

    return f"""\
# bash completion for {prog}
# Generated by: {prog} completion bash
#
# Usage: eval "$({prog} completion bash)"
# Or:    {prog} completion bash > /etc/bash_completion.d/{prog}

_{prog}_completions() {{
    local cur prev words cword
    _init_completion 2>/dev/null || {{
        COMPREPLY=()
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        cword=$COMP_CWORD
        words=("${{COMP_WORDS[@]}}")
    }}

    # Build command path from non-option arguments (skip program name)
    local cmd_path=""
    local i=1
    while [[ $i -lt $cword ]]; do
        local word="${{words[$i]}}"
        case "$word" in
            -*) ;;
            *)
                if [[ -n "$cmd_path" ]]; then
                    cmd_path="${{cmd_path}}_${{word}}"
                else
                    cmd_path="${{word}}"
                fi
                ;;
        esac
        ((i++))
    done

    # Complete options
    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--help --context --api-token" -- "$cur"))
        return
    fi

    # Get completions with descriptions
    local -a completions=()
    case "$cmd_path" in
{cases}
    esac

    # Filter by current word prefix
    local -a matches=()
    local entry comp
    for entry in "${{completions[@]}}"; do
        comp="${{entry%%:*}}"
        if [[ "$comp" == "$cur"* ]]; then
            matches+=("$entry")
        fi
    done

    if [[ ${{#matches[@]}} -eq 0 ]]; then
        return
    elif [[ ${{#matches[@]}} -eq 1 ]]; then
        # Single match - insert just the command word
        COMPREPLY=("${{matches[0]%%:*}}")
    else
        # Multiple matches - show with aligned descriptions
        local maxlen=0
        for entry in "${{matches[@]}}"; do
            comp="${{entry%%:*}}"
            (( ${{#comp}} > maxlen )) && maxlen=${{#comp}}
        done
        local desc min_width=$(( (${{COLUMNS:-80}} + 1) / 2 + 1 ))
        for entry in "${{matches[@]}}"; do
            comp="${{entry%%:*}}"
            desc="${{entry#*:}}"
            printf -v line "%-*s  # %s" "$maxlen" "$comp" "$desc"
            printf -v line "%-*s" "$min_width" "$line"
            COMPREPLY+=("$line")
        done
    fi
}}

complete -o default -F _{prog}_completions {prog}
"""


def _zsh_escape(s: str) -> str:
    """Escape for use inside zsh single quotes."""
    return s.replace("'", "'\\''")


def _generate_zsh(prog: str) -> str:
    tree = _build_tree()

    case_entries: List[str] = []
    for prefix, children in tree.items():
        pattern = prefix.replace(" ", "_") if prefix else ""
        items = "\n".join(
            f"            '{name}:{_zsh_escape(desc)}'" for name, desc in children
        )
        case_entries.append(f'        "{pattern}") commands=(\n{items}\n            ) ;;')

    cases = "\n".join(case_entries)

    return f"""\
#compdef {prog}
# Generated by: {prog} completion zsh
#
# Usage: eval "$({prog} completion zsh)"
# Or:    {prog} completion zsh > ${{fpath[1]}}/_{prog}

_{prog}() {{
    local cmd_path=""
    local i=2
    while [[ $i -lt $CURRENT ]]; do
        case "${{words[$i]}}" in
            -*) ;;
            *) cmd_path="${{cmd_path:+${{cmd_path}}_}}${{words[$i]}}" ;;
        esac
        ((i++))
    done

    if [[ "${{words[$CURRENT]}}" == -* ]]; then
        local -a options=(
            '--help:Display command options and descriptions'
            '--context:Name of authentication context'
            '--api-token:API token to use with BinaryLane API'
        )
        _describe 'option' options
        return
    fi

    local -a commands=()
    case "$cmd_path" in
{cases}
    esac

    _describe 'command' commands
}}

_{prog} "$@"
"""


SHELLS = {"bash": _generate_bash, "zsh": _generate_zsh}


class Command(Runner):
    def run(self, args: List[str]) -> None:
        prog = program_name()

        if not args or args == [Runner.HELP]:
            shells = ", ".join(SHELLS)
            print(f"Usage: {self._context.prog} <{shells}>")
            print()
            print("Generate shell completion scripts.")
            print()
            print("Available shells:")
            print(f"  bash    Generate bash completion script")
            print(f"  zsh     Generate zsh completion script")
            print()
            print(f'Bash: eval "$({prog} completion bash)"')
            print(f'Zsh:  eval "$({prog} completion zsh)"')
            return

        shell = args[0]
        if shell == Runner.CHECK:
            return

        generator = SHELLS.get(shell)
        if generator is None:
            shells = ", ".join(SHELLS)
            print(f"Unsupported shell: {shell}", file=sys.stderr)
            print(f"Supported shells: {shells}", file=sys.stderr)
            raise SystemExit(1)

        print(generator(prog))
